### ISSUE TITLE
bug(event): On ne peut pas mettre de description sur un nouvel event et sousmettrele formulaire

### ISSUE THREAD

**Issue by gdnthomas** [AtelierSoude/OpenRepairPlatform#177]
`Proxy {date: '2022-12-20', publish_at: '2022-12-20T16:54', starts_at: '17:00', ends_at: '18:00', updated: false, …}[[Handler]]: ObjectdeleteProperty: ƒ deleteProperty(target, key)get: ƒ get2(target, key, receiver)has: ƒ has(target, key)ownKeys: ƒ ownKeys(target)set: ƒ set2(target, key, value, receiver)[[Prototype]]: Object[[Target]]: Objectactivity: {model: 'event.activity', pk: 6, fields: {…}}allow_stuffs: trueavailable_seats: 0booking: truecollaborator: ""conditions: [Proxy]date: "2022-12-20"description: Proxy[[Handler]]: ObjectdeleteProperty: ƒ deleteProperty(target, key)get: ƒ get2(target, key, receiver)has: ƒ has(target, key)ownKeys: ƒ ownKeys(target)set: ƒ set2(target, key, value, receiver)[[Prototype]]: Object[[Target]]: Delta[[IsRevoked]]: falseends_at: "18:00"external: falseexternal_url: ""is_free: truelocation: {model: 'location.place', pk: 8632, fields: {…}}members_only: trueneeded_organizers: 0organizers: []publish_at: "2022-12-20T16:54"recurrent: "non"starts_at: "17:00"updated: false[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (…)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()[[IsRevoked]]: false
`
vue.apps.bundle.js:681          POST https://reparons.org/api/event/ 400
Error: Request failed with status code 400
    at createError (vue.apps.bundle.js:331:21)
    at settle (vue.apps.bundle.js:347:18)
    at XMLHttpRequest.onloadend (vue.apps.bundle.js:595:13)

**Comment by gdnthomas** [comment]
Pas de timeout et de formalisme de l'objet envoyé

**Comment by gdnthomas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [On ne peut pas mettre de description sur un event, sinon ça marche pas](https://trello.com/c/kymAaY5I/294-on-ne-peut-pas-mettre-de-description-sur-un-event-sinon-%C3%A7a-marche-pas)
